In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv(r'/storage/emulated/0/Documents/Pydroid3/Case_Information.csv')
df

,case_id,age,age_group,sex,date_announced,date_recovered,date_of_death,status,date_announced_as_removed,province,muni_city,health_status,home_quarantined,date_of_onset_of_symptoms,pregnant,region
0,C404174,38.0,35 to 39,Female,2020-01-30,NaN,NaN,Recovered,2020-02-07,Negros Oriental,Dumaguete City,Recovered,NaN,2020-01-21,NaN,Central Visayas (Region VII)
1,C462688,44.0,40 to 44,Male,2020-02-03,NaN,2020-02-01,Died,2020-02-02,Negros Oriental,Dumaguete City,Died,NaN,2020-01-18,NaN,Central Visayas (Region VII)
2,C387710,60.0,60 to 64,Female,2020-02-05,2020-01-31,NaN,Recovered,2020-02-05,Bohol,Panglao,Recovered,No,2020-01-21,NaN,Central Visayas (Region VII)
3,C377460,48.0,45 to 49,Male,2020-03-06,NaN,NaN,Recovered,2020-03-27,Metropolitan Manila,Taguig,Recovered,No,2020-03-03,NaN,Metropolitan Manila
4,C498051,62.0,60 to 64,Male,2020-03-06,NaN,2020-03-11,Died,2020-03-12,Rizal,Cainta,Died,No,2020-02-25,NaN,CALABARZON (Region IV-A)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12086,C972617,35.0,35 to 39,Male,2020-05-15,NaN,NaN,For validation,NaN,Metropolitan Manila,Makati City,Mild,NaN,NaN,NaN,Metropolitan Manila
12087,C975669,37.0,35 to 39,Male,2020-05-15,NaN,2020-05-13,Died,2020-05-15,Davao del Sur,Davao City,Died,NaN,2020-04-29,NaN,Davao Region (Region XI)
12088,C980530,62.0,60 to 64,Female,2020-05-15,NaN,NaN,For validation,NaN,NaN,NaN,Mild,NaN,NaN,NaN,NaN
12089,C987431,18.0,15 to 19,Female,2020-05-15,NaN,NaN,Home quarantined,NaN,Samar,Tarangnan,Asymptomatic,Yes,NaN,No,Eastern Visayas (Region VIII)
12090,C995671,50.0,50 to 54,Female,2020-05-15,NaN,NaN,For validation,NaN,Quezon,Candelaria,Mild,NaN,NaN,NaN,CALABARZON (Region IV-A)

In [13]:
pd.set_option('display.float_format', lambda x: '%.2f' % x)
df

,case_id,age,age_group,sex,date_announced,date_recovered,date_of_death,status,date_announced_as_removed,province,muni_city,health_status,home_quarantined,date_of_onset_of_symptoms,pregnant,region
0,C404174,38.00,35 to 39,Female,2020-01-30,NaN,NaN,Recovered,2020-02-07,Negros Oriental,Dumaguete City,Recovered,NaN,2020-01-21,NaN,Central Visayas (Region VII)
1,C462688,44.00,40 to 44,Male,2020-02-03,NaN,2020-02-01,Died,2020-02-02,Negros Oriental,Dumaguete City,Died,NaN,2020-01-18,NaN,Central Visayas (Region VII)
2,C387710,60.00,60 to 64,Female,2020-02-05,2020-01-31,NaN,Recovered,2020-02-05,Bohol,Panglao,Recovered,No,2020-01-21,NaN,Central Visayas (Region VII)
3,C377460,48.00,45 to 49,Male,2020-03-06,NaN,NaN,Recovered,2020-03-27,Metropolitan Manila,Taguig,Recovered,No,2020-03-03,NaN,Metropolitan Manila
4,C498051,62.00,60 to 64,Male,2020-03-06,NaN,2020-03-11,Died,2020-03-12,Rizal,Cainta,Died,No,2020-02-25,NaN,CALABARZON (Region IV-A)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12086,C972617,35.00,35 to 39,Male,2020-05-15,NaN,NaN,For validation,NaN,Metropolitan Manila,Makati City,Mild,NaN,NaN,NaN,Metropolitan Manila
12087,C975669,37.00,35 to 39,Male,2020-05-15,NaN,2020-05-13,Died,2020-05-15,Davao del Sur,Davao City,Died,NaN,2020-04-29,NaN,Davao Region (Region XI)
12088,C980530,62.00,60 to 64,Female,2020-05-15,NaN,NaN,For validation,NaN,NaN,NaN,Mild,NaN,NaN,NaN,NaN
12089,C987431,18.00,15 to 19,Female,2020-05-15,NaN,NaN,Home quarantined,NaN,Samar,Tarangnan,Asymptomatic,Yes,NaN,No,Eastern Visayas (Region VIII)
12090,C995671,50.00,50 to 54,Female,2020-05-15,NaN,NaN,For validation,NaN,Quezon,Candelaria,Mild,NaN,NaN,NaN,CALABARZON (Region IV-A)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12091 entries, 0 to 12090
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   case_id                    12091 non-null  object
 1   age                        12070 non-null  float64
 2   age_group                  12070 non-null  object
 3   sex                        12091 non-null  object
 4   date_announced             12091 non-null  object
 5   date_recovered             1237 non-null   object
 6   date_of_death              657 non-null    object
 7   status                     12091 non-null  object
 8   date_announced_as_removed  3266 non-null   object
 9   province                   11053 non-null  object
 10  muni_city                  11053 non-null  object
 11  health_status              12091 non-null  object
 12  home_quarantined           5310 non-null   object
 13  date_of_onset_of_symptoms  6561 non-null   object
 14  pregnant                   1925 non-null   object
 15  region                     11053 non-null  object
dtypes: float64(1), object(15)
memory usage: 1.5+ MB

In [17]:
df.describe()

           age
count 12070.00
mean     44.38
std      18.23
min       0.00
25%      30.00
50%      43.00
75%      58.00
max     101.00

In [19]:
df.isnull().sum()

case_id                          0
age                             21
age_group                       21
sex                              0
date_announced                   0
date_recovered               10854
date_of_death                11434
status                           0
date_announced_as_removed     8825
province                      1038
muni_city                     1038
health_status                    0
home_quarantined              6781
date_of_onset_of_symptoms     5530
pregnant                     10166
region                        1038
dtype: int64

In [20]:
df.nunique()

case_id                      12090
age                            100
age_group                       17
sex                              2
date_announced                  74
date_recovered                  62
date_of_death                   63
status                           5
date_announced_as_removed       68
province                        61
muni_city                      363
health_status                    6
home_quarantined                 2
date_of_onset_of_symptoms       96
pregnant                         2
region                          17
dtype: int64

In [23]:
df.sort_values(by='age', ascending=False).head(10)

,case_id,age,age_group,sex,date_announced,date_recovered,date_of_death,status,date_announced_as_removed,province,muni_city,health_status,home_quarantined,date_of_onset_of_symptoms,pregnant,region
3583,C827192,101.00,80+,Male,2020-04-06,NaN,NaN,For validation,NaN,NaN,NaN,Mild,NaN,NaN,NaN,NaN
11158,C364378,99.00,80+,Male,2020-05-12,NaN,2020-05-03,Died,2020-05-12,NaN,NaN,Died,NaN,2020-04-30,NaN,NaN
1351,C845939,99.00,80+,Male,2020-03-29,NaN,2020-04-02,Died,2020-05-12,Metropolitan Manila,Makati City,Died,No,2020-03-19,NaN,Metropolitan Manila
9423,C810967,99.00,80+,Female,2020-05-04,NaN,NaN,For validation,NaN,Metropolitan Manila,Makati City,Mild,NaN,NaN,NaN,Metropolitan Manila
3962,C474713,97.00,80+,Female,2020-04-09,NaN,NaN,Died,2020-05-14,Metropolitan Manila,Quezon City,Died,No,2020-04-03,NaN,Metropolitan Manila
8561,C302444,96.00,80+,Female,2020-05-01,NaN,NaN,Admitted,NaN,Metropolitan Manila,Manila,Mild,NaN,2020-04-23,NaN,Metropolitan Manila
757,C521779,96.00,80+,Male,2020-03-27,NaN,NaN,Admitted,NaN,Metropolitan Manila,Mandaluyong,Mild,No,2020-03-14,NaN,Metropolitan Manila
6238,C875837,96.00,80+,Female,2020-04-19,NaN,NaN,Admitted,NaN,Metropolitan Manila,Pateros,Mild,NaN,2020-04-11,NaN,Metropolitan Manila
12038,C782011,95.00,80+,Female,2020-05-15,NaN,NaN,For validation,NaN,Batangas,Nasugbu,Mild,NaN,2020-05-05,NaN,CALABARZON (Region IV-A)
4700,C280584,95.00,80+,Female,2020-04-13,NaN,2020-04-21,Died,2020-04-22,Zamboanga del Sur,Zamboanga City,Died,NaN,2020-03-30,No,Zamboanga Peninsula (Region IX)

In [25]:
df.groupby('region').mean().sort_values(by='age')

                                              age
region
Central Visayas (Region VII)                35.88
Cagayan Valley (Region II)                  40.12
Davao Region (Region XI)                    40.82
Zamboanga Peninsula (Region IX)             42.60
Eastern Visayas (Region VIII)               43.21
MIMAROPA (Region IV-B)                      43.54
CALABARZON (Region IV-A)                    44.45
Western Visayas (Region VI)                 45.05
Bicol Region (Region V)                     45.15
Cordillera Administrative Region (CAR)      45.27
Central Luzon (Region III)                  45.45
Metropolitan Manila                         46.73
Northern Mindanao (Region X)                48.24
Caraga (Region XIII)                        48.67
SOCCSKSARGEN (Region XII)                   49.40
Ilocos Region (Region I)                    51.89
Autonomous Region of Muslim Mindanao (ARMM) 53.65

In [31]:
df[df['sex'].str.contains('F')].head(10)

,case_id,age,age_group,sex,date_announced,date_recovered,date_of_death,status,date_announced_as_removed,province,muni_city,health_status,home_quarantined,date_of_onset_of_symptoms,pregnant,region
0,C404174,38.00,35 to 39,Female,2020-01-30,NaN,NaN,Recovered,2020-02-07,Negros Oriental,Dumaguete City,Recovered,NaN,2020-01-21,NaN,Central Visayas (Region VII)
2,C387710,60.00,60 to 64,Female,2020-02-05,2020-01-31,NaN,Recovered,2020-02-05,Bohol,Panglao,Recovered,No,2020-01-21,NaN,Central Visayas (Region VII)
5,C130591,58.00,55 to 59,Female,2020-03-07,NaN,2020-03-12,Died,2020-03-12,Rizal,Cainta,Died,No,2020-02-27,No,CALABARZON (Region IV-A)
10,C261144,68.00,65 to 69,Female,2020-03-09,NaN,NaN,Recovered,2020-03-21,Metropolitan Manila,San Juan,Recovered,Yes,2020-03-02,NaN,Metropolitan Manila
12,C325527,59.00,55 to 59,Female,2020-03-09,2020-04-06,NaN,Recovered,2020-04-08,Bulacan,San Jose del Monte City,Recovered,Yes,2020-03-04,NaN,Central Luzon (Region III)
17,C777589,31.00,30 to 34,Female,2020-03-09,2020-03-24,NaN,Recovered,2020-03-25,Metropolitan Manila,San Juan,Recovered,Yes,2020-03-03,No,Metropolitan Manila
19,C817111,47.00,45 to 49,Female,2020-03-09,2020-03-26,NaN,Recovered,2020-03-28,Metropolitan Manila,Pasig City,Recovered,No,2020-03-07,No,Metropolitan Manila
23,C985840,51.00,50 to 54,Female,2020-03-09,NaN,NaN,Recovered,2020-03-22,Metropolitan Manila,San Juan,Recovered,No,2020-03-04,NaN,Metropolitan Manila
29,C501602,29.00,25 to 29,Female,2020-03-10,2020-03-24,NaN,Recovered,2020-03-25,Metropolitan Manila,San Juan,Recovered,Yes,2020-03-01,NaN,Metropolitan Manila
30,C766724,83.00,80+,Female,2020-03-10,NaN,2020-03-23,Died,2020-03-25,Metropolitan Manila,Marikina,Died,No,2020-03-10,NaN,Metropolitan Manila

In [32]:
df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,12081,12082,12083,12084,12085,12086,12087,12088,12089,12090
case_id,C404174,C462688,C387710,C377460,C498051,C130591,C178743,C202135,C440075,C557002,...,C956141,C960880,C963537,C969474,C971536,C972617,C975669,C980530,C987431,C995671
age,38.00,44.00,60.00,48.00,62.00,58.00,39.00,58.00,33.00,86.00,...,31.00,34.00,53.00,22.00,45.00,35.00,37.00,62.00,18.00,50.00
age_group,35 to 39,40 to 44,60 to 64,45 to 49,60 to 64,55 to 59,35 to 39,55 to 59,30 to 34,80+,...,30 to 34,30 to 34,50 to 54,20 to 24,45 to 49,35 to 39,35 to 39,60 to 64,15 to 19,50 to 54
sex,Female,Male,Female,Male,Male,Female,Male,Male,Male,Male,...,Male,Male,Female,Female,Male,Male,Male,Female,Female,Female
date_announced,2020-01-30,2020-02-03,2020-02-05,2020-03-06,2020-03-06,2020-03-07,2020-03-08,2020-03-08,2020-03-08,2020-03-08,...,2020-05-15,2020-05-15,2020-05-15,2020-05-15,2020-05-15,2020-05-15,2020-05-15,2020-05-15,2020-05-15,2020-05-15
date_recovered,NaN,NaN,2020-01-31,NaN,NaN,NaN,2020-03-21,NaN,2020-04-05,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
date_of_death,NaN,2020-02-01,NaN,NaN,2020-03-11,2020-03-12,NaN,NaN,NaN,2020-03-14,...,NaN,NaN,NaN,NaN,NaN,NaN,2020-05-13,NaN,NaN,NaN
status,Recovered,Died,Recovered,Recovered,Died,Died,Recovered,Recovered,Recovered,Died,...,For validation,For validation,For validation,For validation,For validation,For validation,Died,For validation,Home quarantined,For validation
date_announced_as_removed,2020-02-07,2020-02-02,2020-02-05,2020-03-27,2020-03-12,2020-03-12,2020-03-22,2020-03-25,2020-04-09,2020-03-15,...,NaN,NaN,NaN,NaN,NaN,NaN,2020-05-15,NaN,NaN,NaN
province,Negros Oriental,Negros Oriental,Bohol,Metropolitan Manila,Rizal,Rizal,Metropolitan Manila,Metropolitan Manila,Metropolitan Manila,Metropolitan Manila,...,NaN,Metropolitan Manila,NaN,NaN,Zamboanga del Sur,Metropolitan Manila,Davao del Sur,NaN,Samar,Quezon
muni_city,Dumaguete City,Dumaguete City,Panglao,Taguig,Cainta,Cainta,Makati City,Quezon City,Pasig City,Marikina,...,NaN,Pasay City,NaN,NaN,Zamboanga City,Makati City,Davao City,NaN,Tarangnan,Candelaria
health_status,Recovered,Died,Recovered,Recovered,Died,Died,Recovered,Recovered,Recovered,Died,...,Mild,Mild,Mild,Mild,Mild,Mild,Died,Mild,Asymptomatic,Mild
home_quarantined,NaN,NaN,No,No,No,No,No,NaN,Yes,No,...,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,Yes,NaN
date_of_onset_of_symptoms,2020-01-21,2020-01-18,2020-01-21,2020-03-03,2020-02-25,2020-02-27,2020-03-03,2020-02-20,2020-03-01,2020-03-01,...,NaN,2020-05-05,NaN,NaN,2020-05-05,NaN,2020-04-29,NaN,NaN,NaN
pregnant,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN
region,Central Visayas (Region VII),Central Visayas (Region VII),Central Visayas (Region VII),Metropolitan Manila,CALABARZON (Region IV-A),CALABARZON (Region IV-A),Metropolitan Manila,Metropolitan Manila,Metropolitan Manila,Metropolitan Manila,...,NaN,Metropolitan Manila,NaN,NaN,Zamboanga Peninsula (Region IX),Metropolitan Manila,Davao Region (Region XI),NaN,Eastern Visayas (Region VIII),CALABARZON (Region IV-A)

In [34]:
df.dtypes

case_id                       object
age                          float64
age_group                     object
sex                           object
date_announced                object
date_recovered                object
date_of_death                 object
status                        object
date_announced_as_removed     object
province                      object
muni_city                     object
health_status                 object
home_quarantined              object
date_of_onset_of_symptoms     object
pregnant                      object
region                        object
dtype: object

In [35]:
df.select_dtypes(include='number')

        age
0     38.00
1     44.00
2     60.00
3     48.00
4     62.00
...     ...
12086 35.00
12087 37.00
12088 62.00
12089 18.00
12090 50.00

[12091 rows x 1 columns]

In [36]:
df.select_dtypes(include='object')

,case_id,age_group,sex,date_announced,date_recovered,date_of_death,status,date_announced_as_removed,province,muni_city,health_status,home_quarantined,date_of_onset_of_symptoms,pregnant,region
0,C404174,35 to 39,Female,2020-01-30,NaN,NaN,Recovered,2020-02-07,Negros Oriental,Dumaguete City,Recovered,NaN,2020-01-21,NaN,Central Visayas (Region VII)
1,C462688,40 to 44,Male,2020-02-03,NaN,2020-02-01,Died,2020-02-02,Negros Oriental,Dumaguete City,Died,NaN,2020-01-18,NaN,Central Visayas (Region VII)
2,C387710,60 to 64,Female,2020-02-05,2020-01-31,NaN,Recovered,2020-02-05,Bohol,Panglao,Recovered,No,2020-01-21,NaN,Central Visayas (Region VII)
3,C377460,45 to 49,Male,2020-03-06,NaN,NaN,Recovered,2020-03-27,Metropolitan Manila,Taguig,Recovered,No,2020-03-03,NaN,Metropolitan Manila
4,C498051,60 to 64,Male,2020-03-06,NaN,2020-03-11,Died,2020-03-12,Rizal,Cainta,Died,No,2020-02-25,NaN,CALABARZON (Region IV-A)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12086,C972617,35 to 39,Male,2020-05-15,NaN,NaN,For validation,NaN,Metropolitan Manila,Makati City,Mild,NaN,NaN,NaN,Metropolitan Manila
12087,C975669,35 to 39,Male,2020-05-15,NaN,2020-05-13,Died,2020-05-15,Davao del Sur,Davao City,Died,NaN,2020-04-29,NaN,Davao Region (Region XI)
12088,C980530,60 to 64,Female,2020-05-15,NaN,NaN,For validation,NaN,NaN,NaN,Mild,NaN,NaN,NaN,NaN
12089,C987431,15 to 19,Female,2020-05-15,NaN,NaN,Home quarantined,NaN,Samar,Tarangnan,Asymptomatic,Yes,NaN,No,Eastern Visayas (Region VIII)
12090,C995671,50 to 54,Female,2020-05-15,NaN,NaN,For validation,NaN,Quezon,Candelaria,Mild,NaN,NaN,NaN,CALABARZON (Region IV-A)

In [37]:
df.select_dtypes(include='float')

        age
0     38.00
1     44.00
2     60.00
3     48.00
4     62.00
...     ...
12086 35.00
12087 37.00
12088 62.00
12089 18.00
12090 50.00

[12091 rows x 1 columns]